import {z} from 'zod';
import {db} from '@/lib/db';
import {requireValue} from './security';
import {EMIRATES} from '@/lib/domain';
export async function adminMutation(actor:{id:string;role:string},kind:string,input:unknown){
 requireValue(['OWNER','ADMIN'].includes(actor.role),'This action requires an administrator.',403);
 if(kind==='rewards'){const data=z.object({id:z.string().optional(),name:z.string().min(3).max(100),description:z.string().min(10).max(3000),cost:z.coerce.number().int().min(1).max(100000),quantity:z.coerce.number().int().min(0).max(100000),provider:z.string().min(2).max(100),location:z.string().min(2).max(200),emirate:z.enum(EMIRATES),instructions:z.string().min(10).max(2000),terms:z.string().min(10).max(2000),expiresAt:z.string().transform(s=>new Date(s)).refine(d=>d>new Date()),active:z.boolean().default(true),featured:z.boolean().default(false),demo:z.boolean().default(false),perUserLimit:z.coerce.number().int().min(1).max(10).default(1)}).parse(input);const {id,...values}=data;return db.$transaction(async tx=>{const reward=id?await tx.reward.update({where:{id},data:values}):await tx.reward.create({data:values});await tx.auditLog.create({data:{actorId:actor.id,action:'REWARD_SAVED',target:reward.id,metadata:{}}});return reward;});}
 if(kind==='achievements'){const data=z.object({id:z.string().optional(),name:z.string().min(3).max(80),description:z.string().min(10).max(500),category:z.string().min(2).max(50),requirementType:z.enum(['REPORTS','CLEANUPS','GROUPS','STREAK','POINTS','LESSONS','EVENTS']),requirementValue:z.coerce.number().int().min(1).max(100000),bonus:z.coerce.number().int().min(0).max(100),rarity:z.enum(['COMMON','RARE','EPIC']).default('COMMON'),active:z.boolean().default(true),hidden:z.boolean().default(false)}).parse(input);const {id,...values}=data;return db.$transaction(async tx=>{const a=id?await tx.achievement.update({where:{id},data:values}):await tx.achievement.create({data:values});await tx.auditLog.create({data:{actorId:actor.id,action:'ACHIEVEMENT_SAVED',target:a.id,metadata:{}}});return a;});}
 if(kind==='users'){requireValue(actor.role==='OWNER','Only the owner can manage roles.',403);const data=z.object({id:z.string(),role:z.enum(['VOLUNTEER','ORGANIZATION_MEMBER','ORGANIZATION_ADMIN','MODERATOR','ADMIN']).optional(),banned:z.boolean().optional()}).parse(input);const target=await db.user.findUniqueOrThrow({where:{id:data.id}});requireValue(target.role!=='OWNER'&&target.role!=='CHILD','Owner and child roles cannot be changed here.');return db.$transaction(async tx=>{await tx.user.update({where:{id:data.id},data:{role:data.role,banned:data.banned,sessionVersion:{increment:1}}});await tx.auditLog.create({data:{actorId:actor.id,action:'USER_UPDATED',target:data.id,metadata:data}});return {message:'User permissions updated.'};});}
 if(kind==='organizations'||kind==='places'){const data=z.object({id:z.string(),status:z.enum(['VERIFIED','REJECTED','SUSPENDED','APPROVED'])}).parse(input);requireValue(kind==='places'?['APPROVED','REJECTED'].includes(data.status):['VERIFIED','REJECTED','SUSPENDED'].includes(data.status),'Invalid status.');return db.$transaction(async tx=>{if(kind==='places')await tx.place.update({where:{id:data.id},data:{status:data.status}});else await tx.organization.update({where:{id:data.id},data:{status:data.status}});await tx.auditLog.create({data:{actorId:actor.id,action:`${kind.toUpperCase()}_REVIEWED`,target:data.id,metadata:data}});return {message:'Review recorded.'};});}
 if(kind==='settings'){requireValue(actor.role==='OWNER','Only the owner can change platform settings.',403);const data=z.object({key:z.enum(['rewards','leaderboards','childGames','organizationClaiming','groupEvents','aiAutoApproval','reportPoints','cleanupBasePoints']),value:z.union([z.boolean(),z.number().int().min(0).max(50)])}).parse(input);requireValue(data.key.endsWith('Points')?typeof data.value==='number':typeof data.value==='boolean','Setting value has the wrong type.');return db.$transaction(async tx=>{await tx.setting.upsert({where:{key:data.key},create:data,update:{value:data.value}});await tx.auditLog.create({data:{actorId:actor.id,action:'SETTING_UPDATED',target:data.key,metadata:data}});return {message:'Configuration saved.'};});}
 if(kind==='abuse'){const data=z.object({id:z.string()}).parse(input);return db.$transaction(async tx=>{await tx.abuseReport.update({where:{id:data.id},data:{resolved:true}});await tx.auditLog.create({data:{actorId:actor.id,action:'ABUSE_RESOLVED',target:data.id,metadata:{}}});return {message:'Case resolved.'};});}
 if(kind==='groups'){const data=z.object({id:z.string(),suspended:z.boolean()}).parse(input);return db.$transaction(async tx=>{await tx.group.update({where:{id:data.id},data:{suspended:data.suspended}});await tx.auditLog.create({data:{actorId:actor.id,action:'GROUP_MODERATED',target:data.id,metadata:data}});return {message:'Group updated.'};});}
 if(kind==='challenges'){const data=z.object({name:z.string().min(3).max(100),description:z.string().min(10).max(1000),kind:z.enum(['REPORTS','CLEANUPS']),target:z.coerce.number().int().min(1).max(100),bonus:z.coerce.number().int().min(1).max(100),startsAt:z.string().transform(s=>new Date(s)),endsAt:z.string().transform(s=>new Date(s))}).parse(input);requireValue(data.endsAt>data.startsAt,'Challenge must end after it starts.');return db.$transaction(async tx=>{const c=await tx.challenge.create({data});await tx.auditLog.create({data:{actorId:actor.id,action:'CHALLENGE_CREATED',target:c.id,metadata:{}}});return c;});}
 throw new Error('Unknown administration action');
}
