import {z} from 'zod';
import {db} from '@/lib/db';
import {EMIRATES,LESSONS} from '@/lib/domain';
import {requireValue} from './security';
import {award,achievements} from './points';
const groupSchema=z.object({name:z.string().trim().min(3).max(70),description:z.string().min(20).max(2000),emirate:z.enum(EMIRATES),purpose:z.enum(['CLEAN','REPORT','BOTH','SCHOOL']),rules:z.string().min(10).max(2000),private:z.boolean().default(false)});
export async function createGroup(userId:string,input:unknown){const data=groupSchema.parse(input);const group=await db.group.create({data:{...data,members:{create:{userId,role:'OWNER'}}}});return {id:group.id,message:'Your group is ready.'};}
export async function groupAction(userId:string,id:string,input:unknown){
 const data=z.object({action:z.enum(['join','leave','approve','post']),userId:z.string().optional(),content:z.string().min(2).max(1500).optional()}).parse(input);
 const group=await db.group.findUniqueOrThrow({where:{id}});requireValue(!group.suspended,'This group is not available.');const member=await db.groupMember.findUnique({where:{groupId_userId:{groupId:id,userId}}});
 if(data.action==='join'){await db.groupMember.upsert({where:{groupId_userId:{groupId:id,userId}},create:{groupId:id,userId,status:group.private?'PENDING':'ACTIVE'},update:{}});if(!group.private)await db.$transaction(tx=>achievements(tx,userId));}
 if(data.action==='leave'){requireValue(member?.role!=='OWNER','Group owners must keep their membership.');await db.groupMember.deleteMany({where:{groupId:id,userId}});}
 if(data.action==='approve'){requireValue(member?.status==='ACTIVE'&&['OWNER','ADMIN'].includes(member.role),'Only group administrators can approve members.',403);await db.groupMember.update({where:{groupId_userId:{groupId:id,userId:data.userId!}},data:{status:'ACTIVE'}});}
 if(data.action==='post'){requireValue(member?.status==='ACTIVE'&&data.content,'Join the group before posting.',403);await db.groupPost.create({data:{groupId:id,authorId:userId,content:data.content}});}
 return {message:data.action==='join'&&group.private?'Join request sent.':'Group updated.'};
}
export async function groupDetail(userId:string,id:string){const group=await db.group.findUniqueOrThrow({where:{id},include:{members:{select:{userId:true,role:true,status:true,user:{select:{name:true,username:true}}}},events:{include:{_count:{select:{participants:true}}}}}});requireValue(!group.suspended,'This group is unavailable.',404);const member=group.members.find(m=>m.userId===userId);const canRead=!group.private||member?.status==='ACTIVE';const posts=canRead?await db.groupPost.findMany({where:{groupId:id},orderBy:{createdAt:'desc'},take:50}):[];return {...group,members:canRead?group.members:[],posts,member:member||null};}
export async function createEvent(userId:string,input:unknown){const data=z.object({title:z.string().min(5).max(100),description:z.string().min(15).max(2000),location:z.string().min(5).max(200),emirate:z.enum(EMIRATES),startsAt:z.string().transform(s=>new Date(s)).refine(d=>d>new Date(),'Choose a future date.'),capacity:z.coerce.number().int().min(2).max(500),safety:z.string().min(10).max(1000),bring:z.string().min(3).max(500),groupId:z.string().optional(),organizationId:z.string().optional(),reportIds:z.array(z.string()).max(20).default([])}).parse(input);
 requireValue(data.groupId||data.organizationId,'Choose a group or organization.');if(data.groupId){const member=await db.groupMember.findUnique({where:{groupId_userId:{groupId:data.groupId,userId}}});requireValue(member&&member.status==='ACTIVE'&&['OWNER','ADMIN'].includes(member.role),'Only group administrators can create missions.',403);}if(data.organizationId){const member=await db.organizationMember.findUnique({where:{organizationId_userId:{organizationId:data.organizationId,userId}},include:{organization:true}});requireValue(member?.role==='ADMIN'&&member.organization.status==='VERIFIED','Verified organization administrators can create events.',403);}
 requireValue(await db.trashReport.count({where:{id:{in:data.reportIds},status:'APPROVED',hazardous:false}})===data.reportIds.length,'Missions can only include safe, approved reports.');return db.event.create({data:{...data,creatorId:userId}});
}
export async function rsvp(userId:string,id:string){return db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "Event" WHERE "id"=${id} FOR UPDATE`;const e=await tx.event.findUniqueOrThrow({where:{id},include:{_count:{select:{participants:true}}}});requireValue(e.startsAt>new Date(),'This event has already started.');const existing=await tx.eventParticipant.findUnique({where:{eventId_userId:{eventId:id,userId}}});if(existing){await tx.eventParticipant.delete({where:{eventId_userId:{eventId:id,userId}}});return {message:'RSVP cancelled.'};}requireValue(e._count.participants<e.capacity,'This event is full.');await tx.eventParticipant.create({data:{eventId:id,userId}});return {message:'Your place is reserved.'};});}
export async function lesson(userId:string,input:unknown){const data=z.object({lessonId:z.string(),answer:z.number().int()}).parse(input);const l=LESSONS.find(l=>l.id===data.lessonId);requireValue(l,'Lesson not found.');requireValue(l.answer===data.answer,'Have another look at the lesson and try again.');await db.$transaction(async tx=>{await tx.$queryRaw`SELECT "id" FROM "User" WHERE "id"=${userId} FOR UPDATE`;await tx.lessonResult.upsert({where:{userId_lessonId:{userId,lessonId:l.id}},create:{userId,lessonId:l.id},update:{}});await award(tx,userId,5,'LESSON',`lesson:${userId}:${l.id}`,l.title);await achievements(tx,userId);});return {message:'Lesson complete! Keep growing your knowledge.'};}
