import {NextResponse} from 'next/server';
import {z} from 'zod';
import {db} from '@/lib/db';
import {Prisma} from '@/generated/prisma/client';
import {actor,admin,csrf,AppError,requireValue,rateLimit} from '@/server/security';
import {register,consumeToken,requestToken} from '@/server/accounts';
import {createReport,claim,submitCleanup,moderateReport,moderateCleanup,reportDetail} from '@/server/reports';
import {upload,ownPhoto} from '@/server/uploads';
import {redeem,award,achievements} from '@/server/points';
import {createGroup,groupAction,groupDetail,createEvent,rsvp,lesson} from '@/server/community';
import {adminMutation} from '@/server/admin';
import {EMIRATES,isAdmin,LESSONS} from '@/lib/domain';
type Context={params:Promise<{path:string[]}>};
export const dynamic='force-dynamic';
const safeUser={id:true,name:true,username:true,role:true,createdAt:true,profile:true} as const;
async function feature(key:string){const setting=await db.setting.findUnique({where:{key}});requireValue(setting?.value!==false,'This feature is currently paused.',403);}
async function handle(request:Request,context:Context){
 const {path}=await context.params;const [resource,id,action]=path;const url=new URL(request.url);const write=request.method!=='GET';if(write)csrf(request);
 if(resource==='health') {await db.$queryRaw`SELECT 1`;return {ok:true};}
 if(resource==='accounts'&&write){const body=await request.json();if(id==='register')return register(body);if(id==='verify')return consumeToken(body);if(id==='request-link')return requestToken(body);}
 if(resource==='impact'&&!write){const [cleanups,reports,volunteers,groups]=await Promise.all([db.cleanupAttempt.count({where:{status:'VERIFIED'}}),db.trashReport.count({where:{status:{in:['APPROVED','CLAIMED','AWAITING_VERIFICATION','CLEANED']}}}),db.user.count({where:{verifiedAt:{not:null},banned:false,role:{not:'CHILD'}}}),db.group.count({where:{suspended:false}})]);return {cleanups,reports,volunteers,groups};}
 const user=await actor();if(write)await rateLimit(`write:${user.id}`,100,60);
 if(resource==='me'){
  if(!write)return {...await db.user.findUniqueOrThrow({where:{id:user.id},select:safeUser}),email:user.email,organizations:await db.organizationMember.findMany({where:{userId:user.id},include:{organization:true}}),levels:await db.level.findMany({orderBy:{minimumPoints:'asc'}}),settings:await db.setting.findMany()};
  const data=z.object({name:z.string().trim().min(2).max(60),bio:z.string().max(500),emirate:z.enum(EMIRATES),interest:z.enum(['CLEAN','REPORT','BOTH','EXPLORE']),theme:z.enum(['light','dark','system']),publicProfile:z.boolean(),leaderboard:z.boolean(),notifications:z.boolean()}).parse(await request.json());const {name,...profile}=data;if(user.role==='CHILD'){profile.publicProfile=false;profile.leaderboard=false;}await db.user.update({where:{id:user.id},data:{name,profile:{update:profile}}});return {message:'Your preferences are saved.'};
 }
 if(resource==='sessions'&&write){await db.user.update({where:{id:user.id},data:{sessionVersion:{increment:1}}});return {message:'All sessions revoked. Please sign in again.'};}
 if(resource==='export'&&!write){return {account:{id:user.id,email:user.email,name:user.name,username:user.username,profile:user.profile},reports:await db.trashReport.findMany({where:{reporterId:user.id}}),cleanups:await db.cleanupAttempt.findMany({where:{cleanerId:user.id}}),transactions:await db.pointTransaction.findMany({where:{userId:user.id}}),redemptions:await db.rewardRedemption.findMany({where:{userId:user.id}})};}
 if(resource==='delete-account'&&write){const data=z.object({confirmation:z.literal('DELETE')}).parse(await request.json());requireValue(user.role!=='OWNER','Transfer ownership before closing the owner account.');await db.$transaction(async tx=>{await tx.user.update({where:{id:user.id},data:{name:'Deleted member',username:`deleted_${user.id}`,email:`${user.id}@deleted.invalid`,passwordHash:'deleted',banned:true,sessionVersion:{increment:1},profile:{update:{bio:'',area:'',avatarId:null,bannerId:null,publicProfile:false,leaderboard:false}}}});await tx.childProfile.deleteMany({where:{userId:user.id}});await tx.authToken.deleteMany({where:{userId:user.id}});await tx.notification.deleteMany({where:{userId:user.id}});await tx.groupPost.updateMany({where:{authorId:user.id},data:{content:'Content removed by account owner.'}});await tx.auditLog.create({data:{actorId:user.id,action:'ACCOUNT_CLOSED',target:user.id,metadata:{confirmation:data.confirmation}}});});return {message:'Account closed and personal profile anonymized. Environmental and accounting records are retained.'};}
 if(resource==='uploads'&&write){await rateLimit(`upload:${user.id}`,30,3600);const form=await request.formData();const file=form.get('file');requireValue(file instanceof File,'Select a photo.');return upload(user.id,file);}
 if(resource==='dashboard'&&!write){const [reports,cleanups,notifications,transactions,unlocks,groups,events,challenges]=await Promise.all([db.trashReport.findMany({where:{reporterId:user.id},orderBy:{createdAt:'desc'},take:20}),db.cleanupAttempt.findMany({where:{cleanerId:user.id},include:{report:true},orderBy:{claimedAt:'desc'},take:20}),db.notification.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:5}),db.pointTransaction.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:30}),db.userAchievement.findMany({where:{userId:user.id},include:{achievement:true}}),db.groupMember.findMany({where:{userId:user.id,status:'ACTIVE'},include:{group:true}}),db.event.findMany({where:{startsAt:{gte:new Date()}},orderBy:{startsAt:'asc'},take:3,include:{_count:{select:{participants:true}}}}),db.challenge.findMany({where:{active:true,endsAt:{gte:new Date()}},take:4})]);return {reports,cleanups,notifications,transactions,unlocks,groups,events,challenges};}
 if(resource==='reports'){
  requireValue(user.role!=='CHILD','Explore eco lessons with your guardian. The live reporting map is for volunteers.',403);
  if(write){if(!id)return createReport(user,await request.json());if(action==='claim')return claim(user,id);if(action==='save'){const key={userId_reportId:{userId:user.id,reportId:id}};const exists=await db.savedReport.findUnique({where:key});if(exists)await db.savedReport.delete({where:key});else await db.savedReport.create({data:{userId:user.id,reportId:id}});return {message:exists?'Removed from saved reports.':'Report saved.'};}if(action==='confirm'){const data=z.object({kind:z.enum(['STILL_THERE','LOOKS_CLEANED'])}).parse(await request.json());await reportDetail(id,user);await db.confirmation.upsert({where:{userId_reportId:{userId:user.id,reportId:id}},create:{userId:user.id,reportId:id,kind:data.kind},update:{kind:data.kind}});return {message:'Your observation was recorded for moderators.'};}}
  if(id)return reportDetail(id,user);
  const bounds=z.object({north:z.coerce.number().min(-90).max(90),south:z.coerce.number().min(-90).max(90),east:z.coerce.number().min(-180).max(180),west:z.coerce.number().min(-180).max(180)}).parse({north:url.searchParams.get('north')||26.2,south:url.searchParams.get('south')||22.6,east:url.searchParams.get('east')||56.6,west:url.searchParams.get('west')||51.4});requireValue(bounds.north>=bounds.south&&bounds.east>=bounds.west,'Invalid map bounds.');
  const status=url.searchParams.get('status');const where:Prisma.TrashReportWhereInput={latitude:{gte:bounds.south,lte:bounds.north},longitude:{gte:bounds.west,lte:bounds.east},status:{in:['APPROVED','CLAIMED','AWAITING_VERIFICATION','CLEANED']}};
  if(status&&['APPROVED','CLAIMED','AWAITING_VERIFICATION','CLEANED'].includes(status))where.status=status as 'APPROVED';if(url.searchParams.get('category'))where.category=url.searchParams.get('category')!;if(url.searchParams.get('mine')==='true'){where.reporterId=user.id;delete where.status;}if(url.searchParams.get('saved')==='true')where.saved={some:{userId:user.id}};
  return db.trashReport.findMany({where,orderBy:{createdAt:'desc'},take:200,select:{id:true,title:true,description:true,category:true,severity:true,latitude:true,longitude:true,address:true,emirate:true,photoId:true,hazardous:true,status:true,createdAt:true}});
 }
 if(resource==='cleanups'&&write&&id){if(action==='proof')return submitCleanup(user.id,id,await request.json());if(action==='cancel'){return db.$transaction(async tx=>{const c=await tx.cleanupAttempt.findUniqueOrThrow({where:{id}});requireValue(c.cleanerId===user.id&&c.status==='CLAIMED','Only your active claim can be cancelled.',403);const result=await tx.cleanupAttempt.updateMany({where:{id,status:'CLAIMED'},data:{status:'CANCELLED'}});requireValue(result.count===1,'Claim already changed.',409);await tx.trashReport.update({where:{id:c.reportId},data:{status:'APPROVED'}});return {message:'Claim cancelled.'};});}}
 if(resource==='achievements'&&!write){return db.achievement.findMany({where:{active:true,OR:[{hidden:false},{users:{some:{userId:user.id}}}]},include:{users:{where:{userId:user.id},select:{unlockedAt:true}}}});}
 if(resource==='rewards'){await feature('rewards');if(write&&id){const input=z.object({requestKey:z.string().uuid()}).parse(await request.json());return redeem(user.id,id,input.requestKey);}return {rewards:await db.reward.findMany({where:{active:true,expiresAt:{gt:new Date()}},orderBy:{featured:'desc'}}),redemptions:await db.rewardRedemption.findMany({where:{userId:user.id},include:{reward:true},orderBy:{createdAt:'desc'}})};}
 if(resource==='notifications'){if(write){await db.notification.updateMany({where:{userId:user.id,...(id?{id}:{})},data:{read:true}});return {message:'Notifications marked as read.'};}return db.notification.findMany({where:{userId:user.id},orderBy:{createdAt:'desc'},take:100});}
 if(resource==='groups'){requireValue(user.role!=='CHILD','Public groups are not available for child accounts.',403);if(write){if(id)return groupAction(user.id,id,await request.json());return createGroup(user.id,await request.json());}if(id)return groupDetail(user.id,id);return db.group.findMany({where:{suspended:false,...(url.searchParams.get('q')?{name:{contains:url.searchParams.get('q')!,mode:'insensitive'}}:{}),...(url.searchParams.get('emirate')?{emirate:url.searchParams.get('emirate')!}:{})},include:{_count:{select:{members:{where:{status:'ACTIVE'}}}},members:{where:{userId:user.id},select:{status:true,role:true}}},take:60,orderBy:{createdAt:'desc'}});}
 if(resource==='events'){await feature('groupEvents');requireValue(user.role!=='CHILD','Children participate in supervised activities through their guardian.',403);if(write){if(id&&action==='attendance'){const data=z.object({userId:z.string()}).parse(await request.json());const e=await db.event.findUniqueOrThrow({where:{id}});requireValue(e.creatorId===user.id||isAdmin(user.role),'Only the organizer can record attendance.',403);requireValue(e.startsAt<new Date(),'Attendance can only be confirmed after the event begins.');await db.$transaction(async tx=>{await tx.eventParticipant.update({where:{eventId_userId:{eventId:id,userId:data.userId}},data:{attended:true}});await award(tx,data.userId,15,'EVENT',`event:${id}:${data.userId}`,e.title);await achievements(tx,data.userId);});return {message:'Attendance confirmed.'};}if(id)return rsvp(user.id,id);return createEvent(user.id,await request.json());}return db.event.findMany({where:{startsAt:{gte:new Date(Date.now()-86400000)}},orderBy:{startsAt:'asc'},take:60,include:{group:{select:{name:true}},organization:{select:{name:true}},_count:{select:{participants:true}},participants:{where:{userId:user.id},select:{attended:true}}}});}
 if(resource==='lessons'){await feature('childGames');if(write)return lesson(user.id,await request.json());return {lessons:LESSONS.map(l=>({id:l.id,title:l.title,topic:l.topic,intro:l.intro,question:l.question,options:l.options})),completed:await db.lessonResult.findMany({where:{userId:user.id}})};}
 if(resource==='leaderboard'){await feature('leaderboards');return db.user.findMany({where:{role:{not:'CHILD'},banned:false,profile:{leaderboard:true,publicProfile:true}},select:{name:true,username:true,profile:{select:{lifetimePoints:true,emirate:true}}},orderBy:{profile:{lifetimePoints:'desc'}},take:50});}
 if(resource==='organizations'){
  requireValue(user.role!=='CHILD','Organization tools are for adult organizers.',403);
  if(write){const member=await db.organizationMember.findUnique({where:{organizationId_userId:{organizationId:id,userId:user.id}}});requireValue(member?.role==='ADMIN','Organization administrator access is required.',403);const body=await request.json();if(action==='places'){await feature('organizationClaiming');const data=z.object({name:z.string().min(3).max(100),address:z.string().min(5).max(200),latitude:z.coerce.number().min(22.6).max(26.2),longitude:z.coerce.number().min(51.4).max(56.6),radiusMeters:z.coerce.number().int().min(10).max(200),proofId:z.string()}).parse(body);await ownPhoto(user.id,data.proofId);return db.place.create({data:{...data,organizationId:id}});}if(action==='staff'){const data=z.object({email:z.email()}).parse(body);const staff=await db.user.findUnique({where:{email:data.email.toLowerCase()}});requireValue(staff&&staff.role!=='CHILD','A registered adult account is required.');return db.organizationMember.upsert({where:{organizationId_userId:{organizationId:id,userId:staff.id}},create:{organizationId:id,userId:staff.id},update:{}});}const data=z.object({description:z.string().min(20).max(2000),website:z.union([z.url().refine(v=>v.startsWith('https://')),z.literal('')]),proofId:z.string()}).parse(body);await ownPhoto(user.id,data.proofId);return db.organization.update({where:{id},data:{...data,status:'PENDING'}});}
  if(id){const member=await db.organizationMember.findUnique({where:{organizationId_userId:{organizationId:id,userId:user.id}}});const org=await db.organization.findUniqueOrThrow({where:{id},include:{places:{include:{reports:{where:{status:{in:['APPROVED','CLAIMED','AWAITING_VERIFICATION','CLEANED']}},take:30}}},members:{select:{userId:true,role:true,user:{select:{name:true}}}}}});requireValue(org.status==='VERIFIED'||member||isAdmin(user.role),'This organization is awaiting verification.',403);return {...org,members:member?org.members:[],proofId:member?org.proofId:null,member};}
  return db.organization.findMany({where:{OR:[{status:'VERIFIED'},{members:{some:{userId:user.id}}}]},select:{id:true,name:true,description:true,emirate:true,status:true,type:true},take:50});
 }
 if(resource==='abuse'&&write){const data=z.object({targetType:z.enum(['REPORT','GROUP','USER','PHOTO','ORGANIZATION']),targetId:z.string(),reason:z.enum(['SPAM','HARASSMENT','FAKE_REPORT','DANGEROUS_CONTENT','INAPPROPRIATE_IMAGE','DUPLICATE','FRAUD','OTHER']),details:z.string().min(5).max(1000)}).parse(await request.json());await db.abuseReport.create({data:{...data,reporterId:user.id}});return {message:'Your safety report has been sent to moderators.'};}
 if(resource==='search'&&!write){requireValue(user.role!=='CHILD','Search is restricted for child accounts.',403);const q=(url.searchParams.get('q')||'').slice(0,80);if(q.length<2)return [];const [reports,groups,rewards,organizations,events]=await Promise.all([db.trashReport.findMany({where:{title:{contains:q,mode:'insensitive'},status:{in:['APPROVED','CLAIMED','CLEANED']}},take:8}),db.group.findMany({where:{name:{contains:q,mode:'insensitive'},suspended:false},take:8}),db.reward.findMany({where:{name:{contains:q,mode:'insensitive'},active:true},take:8}),db.organization.findMany({where:{name:{contains:q,mode:'insensitive'},status:'VERIFIED'},take:8}),db.event.findMany({where:{title:{contains:q,mode:'insensitive'}},take:8})]);return [...reports.map(r=>({name:r.title,type:'Report',href:`/map?report=${r.id}`})),...groups.map(g=>({name:g.name,type:'Group',href:`/groups/${g.id}`})),...rewards.map(r=>({name:r.name,type:'Reward',href:'/rewards'})),...organizations.map(o=>({name:o.name,type:'Organization',href:`/organizations/${o.id}`})),...events.map(e=>({name:e.title,type:'Event',href:'/events'}))];}
 if(resource==='places-search'){await rateLimit(`geocode:${user.id}`,1,2);const q=(url.searchParams.get('q')||'').slice(0,100);requireValue(q.length>=3,'Enter at least three characters.');const result=await fetch(`https://nominatim.openstreetmap.org/search?format=json&countrycodes=ae&limit=5&q=${encodeURIComponent(q)}`,{headers:{'User-Agent':`GoGreenUAE/1.0 (${process.env.NEXTAUTH_URL||'local development'})`},signal:AbortSignal.timeout(6000)});requireValue(result.ok,'Place search is unavailable. Move the map manually.',503);return result.json();}
 if(resource==='admin'){
  const a=await admin();if(write){const body=await request.json();if(id==='reports'){const data=z.object({id:z.string(),decision:z.enum(['APPROVE','REJECT','DUPLICATE']),reason:z.string().min(5).max(1000)}).parse(body);return moderateReport(a.id,data.id,data.decision,data.reason);}if(id==='cleanups'){const data=z.object({id:z.string(),approve:z.boolean(),reason:z.string().min(5).max(1000)}).parse(body);return moderateCleanup(a.id,data.id,data.approve,data.reason);}return adminMutation(a,id,body);}
  if(id==='reports')return db.trashReport.findMany({where:{status:'PENDING_REVIEW'},include:{reviews:true},take:100});
  if(id==='cleanups')return db.cleanupAttempt.findMany({where:{status:'PENDING_REVIEW'},include:{report:{include:{reviews:true}}},take:100});
  if(id==='users')return db.user.findMany({select:{...safeUser,banned:true,verifiedAt:true},orderBy:{createdAt:'desc'},take:100});
  if(id==='rewards')return db.reward.findMany({take:100});if(id==='achievements')return db.achievement.findMany({take:100});if(id==='organizations')return db.organization.findMany({take:100});if(id==='places')return db.place.findMany({include:{organization:{select:{name:true}}},take:100});if(id==='audit')return db.auditLog.findMany({orderBy:{createdAt:'desc'},take:100});if(id==='abuse')return db.abuseReport.findMany({where:{resolved:false},take:100});if(id==='groups')return db.group.findMany({take:100});if(id==='settings')return db.setting.findMany();
  return {users:await db.user.count(),reports:await db.trashReport.count(),pending:await db.trashReport.count({where:{status:'PENDING_REVIEW'}}),cleanups:await db.cleanupAttempt.count({where:{status:'VERIFIED'}}),redemptions:await db.rewardRedemption.count()};
 }
 throw new AppError(404,'This page or action could not be found.');
}
async function route(request:Request,context:Context){try{return NextResponse.json(await handle(request,context),{headers:{'Cache-Control':'no-store'}});}catch(error){if(error instanceof AppError)return NextResponse.json({error:error.message},{status:error.status});if(error instanceof z.ZodError)return NextResponse.json({error:error.issues.map(i=>i.message).join(' ')},{status:400});if(error instanceof Prisma.PrismaClientKnownRequestError){if(error.code==='P2002')return NextResponse.json({error:'This action was already recorded or the value is already in use.'},{status:409});if(error.code==='P2025')return NextResponse.json({error:'The requested item was not found.'},{status:404});}console.error(JSON.stringify({event:'api_error',path:new URL(request.url).pathname,error:error instanceof Error?error.name:'Unknown',code:error instanceof Prisma.PrismaClientKnownRequestError?error.code:undefined}));return NextResponse.json({error:'Something went wrong. Your request could not be completed. Please try again.'},{status:500});}}
export {route as GET,route as POST};
