import {notFound} from 'next/navigation';
import Link from 'next/link';
import {Brand} from '@/components/ui';
const pages:Record<string,{title:string;intro:string;sections:{title:string;text:string}[]}>= {
 privacy:{title:'Your privacy matters',intro:'GoGreen UAE collects only the information needed to run accounts, review environmental evidence, and record community impact.',sections:[{title:'What we store',text:'Account email, password hash, profile preferences, report and cleanup evidence, point transactions, and administrative audit history. Child dates of birth and guardian approval are private. We do not track continuous movement.'},{title:'Locations and photos',text:'Report locations become visible to signed-in volunteers after review. Never upload private home locations or identifiable people without permission. Image metadata is removed during processing. Child accounts cannot publish exact locations.'},{title:'Your controls',text:'Public recognition and leaderboards are opt-in. Download your account data or close your account in Settings. Closing an account anonymizes the profile; environmental evidence and accounting records remain for integrity.'},{title:'Service providers',text:'The application and database are hosted on Render. Map requests go to OpenStreetMap services. If an AI reviewer is configured, submitted evidence is sent to that configured provider for review. Email addresses are sign-in identifiers. No verification or reset emails are sent; password recovery uses private one-use recovery codes.'}]},
 terms:{title:'Terms of participation',intro:'GoGreen UAE is an independent competition project. Participation is voluntary, and no government endorsement or partnership is implied.',sections:[{title:'Responsible participation',text:'Provide accurate information and genuine photos. Do not stage litter, reuse evidence, harass others, or create accounts to farm points. Moderators may reject content or suspend accounts.'},{title:'Safety comes first',text:'Only perform cleanups appropriate for your age, ability, and conditions. Never handle hazardous materials or enter private property without permission. The platform does not replace emergency services or official municipal reporting.'},{title:'Points and availability',text:'Eco Points have no cash value. Rewards depend on published availability and specific terms. Free hosting may sleep or become temporarily unavailable. Demonstration rewards are clearly labeled and cannot be used commercially.'}]},
 community:{title:'A community built on care',intro:'Be kind to people, thoughtful about places, and honest about your impact.',sections:[{title:'Respect people and places',text:'Use neutral descriptions of environmental issues. Do not shame organizations, reveal personal information, or post identifiable images of children. Ask before entering managed or private spaces.'},{title:'Keep evidence honest',text:'Use your own current photos. Do not alter images to misrepresent an area, duplicate reports, or claim work you did not perform. Community observations support moderation but do not replace verification.'},{title:'Raise a concern',text:'Use “Report a concern” on a report to send spam, fraud, harassment, or safety concerns to the moderation queue. Immediate danger belongs with the appropriate local authority.'}]},
 'child-safety':{title:'A safer space for young explorers',intro:'Under-12 accounts require guardian approval and default to private.',sections:[{title:'Guardian involvement',text:'A parent or guardian creates their own account first and approves the child account from Settings before the child can sign in. Use a guardian-controlled account email and keep the child account recovery code private. Guardians can help the child reset their password using the recovery code, download account data, and close the account.'},{title:'Protective boundaries',text:'Child accounts do not have private messaging, public group discovery, live reporting maps, public leaderboards, or volunteer cleanup claims. Environmental lessons and achievement progress are available in a simpler interface.'},{title:'Learning together',text:'Children should explore environmental activities with a trusted adult. A guardian can report litter using their own account. Never encourage a child to touch dangerous waste or share a home or school location.'}]},
 safety:{title:'Care for the planet. Care for yourself.',intro:'A safe report is always more valuable than a risky cleanup.',sections:[{title:'Do not touch hazardous waste',text:'Keep away from needles, medical waste, chemicals, unknown liquids, dead animals, dangerous construction materials, and roadway hazards. Report these to the appropriate local authority. Hazardous reports cannot be claimed as ordinary volunteer cleanups.'},{title:'Prepare for conditions',text:'Wear suitable gloves and closed shoes. Carry water, consider the heat, and choose safe daylight conditions. Work with others when appropriate. Stop if conditions become unsafe.'},{title:'Respect access and wildlife',text:'Stay on public paths or obtain permission. Avoid disturbing wildlife, mangroves, dunes, and protected areas. Do not enter water, unstable terrain, roads, or construction sites to earn points.'}]},
 rewards:{title:'Reward terms',intro:'Rewards recognize verified community participation. Eco Points are not money.',sections:[{title:'Availability and limits',text:'Each reward lists its point cost, quantity, expiry, provider, instructions, and per-user conditions. Redemption checks stock and balance together. Repeated requests do not create duplicate redemptions.'},{title:'Your redemption proof',text:'Keep your unique code private. Follow the stated provider instructions. A code alone does not imply any third-party sponsorship beyond the published reward terms.'},{title:'Demonstration offers',text:'Competition demonstration rewards are explicitly marked. They have no cash value and cannot be exchanged with real shops or providers. Only genuine, approved sponsor offers should be published as real rewards.'}]}
};
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;return {title:pages[slug]?.title||'Policy'};}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug];if(!page)notFound();return <main className="policy" id="main-content"><Brand/><p className="eyebrow">OUR SHARED RESPONSIBILITY</p><h1>{page.title}</h1><p>{page.intro}</p><div className="notice">Competition draft · Final legal and operational review is required before a public production launch.</div>{page.sections.map(s=><section key={s.title}><h2>{s.title}</h2><p>{s.text}</p></section>)}<div className="policy-links" style={{marginTop:35}}>{Object.entries(pages).map(([key,p])=><Link className="tag" href={`/policies/${key}`} key={key}>{p.title}</Link>)}</div></main>;}
