import 'dotenv/config';
import {hash} from 'bcryptjs';
import {randomBytes} from 'node:crypto';
import {db} from '../src/lib/db';
import {deliverToken} from '../src/server/accounts';
async function main(){
 const levels=[['Seed',0],['Sprout',50],['Green Helper',150],['Eco Explorer',350],['Community Cleaner',700],['Eco Guardian',1200],['Planet Protector',2500],['Green Champion',5000]] as const;
 for(const [i,[name,minimumPoints]] of levels.entries())await db.level.upsert({where:{id:i+1},create:{id:i+1,name,minimumPoints},update:{}});
 const definitions=[['first-report','First Report','Your first reviewed report helped someone find a place to care for.','REPORTS',1,5],['eco-spotter','Eco Spotter','Ten approved reports. Ten chances to make a difference.','REPORTS',10,20],['cleanup-hero','Cleanup Hero','Complete your first verified cleanup.','CLEANUPS',1,10],['pro-volunteer','Pro Volunteer','Leave ten places better than you found them.','CLEANUPS',10,30],['team-player','Team Player','Join a community and grow together.','GROUPS',1,0],['steady-sprout','Steady Sprout','Three days of meaningful environmental action.','STREAK',3,10],['recycling-rookie','Recycling Rookie','Complete your first eco lesson.','LESSONS',1,5],['eco-genius','Eco Genius','Complete all four environmental lessons.','LESSONS',4,10]] as const;
 for(const [id,name,description,requirementType,requirementValue,bonus] of definitions)await db.achievement.upsert({where:{id},create:{id,name,description,requirementType,requirementValue,bonus,category:requirementType},update:{}});
 for(const [key,value] of Object.entries({rewards:true,leaderboards:true,childGames:true,organizationClaiming:true,groupEvents:true,aiAutoApproval:false,reportPoints:10,cleanupBasePoints:20}))await db.setting.upsert({where:{key},create:{key,value},update:{}});
 if(process.env.OWNER_EMAIL){const email=process.env.OWNER_EMAIL.toLowerCase();const existing=await db.user.findUnique({where:{email}});if(!existing){const production=process.env.NODE_ENV==='production';if(production&&!process.env.SMTP_HOST)throw new Error('Configure SMTP before production owner initialization.');const owner=await db.user.create({data:{email,name:'David',username:'david_owner',role:'OWNER',passwordHash:await hash(randomBytes(40).toString('hex'),12),verifiedAt:new Date(),profile:{create:{onboardingComplete:true}}}});await deliverToken(owner.id,email,'RESET');console.log('Owner initialization email queued.');}else if(existing.role!=='OWNER')throw new Error('OWNER_EMAIL matches a non-owner account; refusing automatic privilege escalation.');}
 if(process.env.SEED_DEMO==='true'){
  if(process.env.NODE_ENV==='production')throw new Error('Development demo credentials are prohibited in production.');
  for(const [email,name,username,role] of [['david@example.test','David','david','OWNER'],['sara@example.test','Sara','sara','VOLUNTEER'],['omar@example.test','Omar','omar','VOLUNTEER'],['explorer@example.test','Eco Explorer','explorer','CHILD'],['organizer@example.test','Maya','maya','ORGANIZATION_ADMIN']] as const){await db.user.upsert({where:{email},create:{email,name,username,role,passwordHash:await hash('GoGreen-demo-2026!',12),verifiedAt:new Date(),profile:{create:{onboardingComplete:true,emirate:'Dubai'}},...(role==='CHILD'?{child:{create:{birthDate:new Date('2017-01-01'),guardianEmail:'guardian@example.test',approvedAt:new Date()}}}:{})},update:{}});}
  const sara=await db.user.findUniqueOrThrow({where:{email:'sara@example.test'}});
  for(const [id,name,emirate] of [['demo-coastal','Coastal Care Collective','Dubai'],['demo-desert','Desert Footprints','Ras Al Khaimah'],['demo-parks','Our Neighborhood, Greener','Abu Dhabi']])await db.group.upsert({where:{id},create:{id,name,emirate,purpose:'BOTH',description:'Demonstration community for people who care about clean public spaces, mindful volunteering, and a greener shared future.',rules:'Be kind, respect privacy, and put safety before points.',members:{create:{userId:sara.id,role:'OWNER'}}},update:{}});
  await db.reward.upsert({where:{id:'demo-reward'},create:{id:'demo-reward',name:'Community thank-you voucher',description:'A demonstration of the secure reward journey. This is not a real commercial offer.',cost:30,quantity:100,provider:'GoGreen Demo Collective',location:'Competition demonstration',emirate:'Dubai',instructions:'Show this unique code to the demo administrator to demonstrate redemption.',terms:'Demonstration only. No cash value. No real sponsor or retail redemption.',expiresAt:new Date('2028-12-31'),demo:true},update:{}});
  console.log('Development demo accounts seeded. Password: documented in README.');
 }
 console.log('Seed complete.');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;}).finally(()=>db.$disconnect());
