import 'dotenv/config';
import test from 'node:test';
import assert from 'node:assert/strict';
import sharp from 'sharp';
import {readFile} from 'node:fs/promises';
import {db} from '../../src/lib/db';
const base='http://localhost:3000';
class Client{
 cookies=new Map<string,string>();
 async request(path:string,body?:unknown){const headers:Record<string,string>={Origin:base,Cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; ')};if(body!==undefined&&!(body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch(`${base}${path}`,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:body instanceof FormData?body:JSON.stringify(body),redirect:'manual'});for(const cookie of response.headers.getSetCookie()){const pair=cookie.split(';')[0];const index=pair.indexOf('=');this.cookies.set(pair.slice(0,index),pair.slice(index+1));}const text=await response.text();let result;try{result=JSON.parse(text);}catch{result={text};}return {status:response.status,data:result};}
 async login(email:string){const csrf=await this.request('/api/auth/csrf');const response=await fetch(`${base}/api/auth/callback/credentials`,{method:'POST',headers:{Origin:base,Cookie:[...this.cookies].map(([k,v])=>`${k}=${v}`).join('; '),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({csrfToken:csrf.data.csrfToken,email,password:'GoGreen-demo-2026!',json:'true',callbackUrl:`${base}/home`}),redirect:'manual'});for(const cookie of response.headers.getSetCookie()){const pair=cookie.split(';')[0];const index=pair.indexOf('=');this.cookies.set(pair.slice(0,index),pair.slice(index+1));}assert.equal((await this.request('/api/v1/me')).status,200);}
}
test('complete account → report → independent moderation → cleanup → points → reward journey',async()=>{
 const unique=Date.now();const reporter=new Client();const cleaner=new Client();const owner=new Client();
 async function signup(client:Client,name:string){const email=`${name}-${unique}@example.test`;const response=await client.request('/api/v1/accounts/register',{email,password:'GoGreen-demo-2026!',name,username:`${name}${unique}`,kind:'VOLUNTEER',birthDate:'2000-01-01',emirate:'Dubai',interest:'BOTH'});assert.equal(response.status,200,JSON.stringify(response.data));const mail=(await readFile('.local/mail.jsonl','utf8')).trim().split('\n').map(s=>JSON.parse(s)).findLast(m=>m.email===email);const token=new URL(mail.url).searchParams.get('token');assert.equal((await client.request('/api/v1/accounts/verify',{token})).status,200);assert.equal((await client.request('/api/v1/accounts/verify',{token})).status,400);await client.login(email);return email;}
 await signup(reporter,'sara');await signup(cleaner,'omar');await owner.login('david@example.test');
 assert.equal((await reporter.request('/api/v1/admin/users')).status,403);
 const reporterMe=(await reporter.request('/api/v1/me')).data;const cleanerMe=(await cleaner.request('/api/v1/me')).data;
 async function photo(client:Client,color:string){const bytes=await sharp({create:{width:500,height:350,channels:3,background:color}}).png().toBuffer();const form=new FormData();form.set('file',new File([new Uint8Array(bytes)],'test-evidence.png',{type:'image/png'}));const r=await client.request('/api/v1/uploads',form);assert.equal(r.status,200,JSON.stringify(r.data));return r.data.id;}
 const before=await photo(reporter,`#${(unique%0xffffff).toString(16).padStart(6,'0')}`);const longitude=55.27+(unique%10000)/1000000;
 const report=await reporter.request('/api/v1/reports',{title:'Integration test report',description:'Test evidence for the verified environmental workflow.',category:'Plastic',severity:3,latitude:25.20+(unique%10000)/1000000,longitude,address:'Local test park',emirate:'Dubai',photoId:before});assert.equal(report.status,200,JSON.stringify(report.data));const id=report.data.id;
 const pending=await db.trashReport.findUniqueOrThrow({where:{id}});assert.equal(pending.status,'PENDING_REVIEW');assert.equal((await db.profile.findUniqueOrThrow({where:{userId:reporterMe.id}})).balance,0);
 assert.equal((await cleaner.request(`/api/v1/reports/${id}/claim`,{})).status,409);
 const approved=await owner.request('/api/v1/admin/reports',{id,decision:'APPROVE',reason:'Test evidence independently reviewed.'});assert.equal(approved.status,200,JSON.stringify(approved.data));assert.equal((await owner.request('/api/v1/admin/reports',{id,decision:'APPROVE',reason:'Duplicate approval attempt.'})).status,409);
 const claim=await cleaner.request(`/api/v1/reports/${id}/claim`,{});assert.equal(claim.status,200,JSON.stringify(claim.data));assert.equal((await reporter.request(`/api/v1/reports/${id}/claim`,{})).status,409);
 const after=await photo(cleaner,`#${((unique+9999)%0xffffff).toString(16).padStart(6,'0')}`);const proof=await cleaner.request(`/api/v1/cleanups/${claim.data.id}/proof`,{afterPhotoId:after,notes:'Test cleanup evidence',safe:true});assert.equal(proof.status,200,JSON.stringify(proof.data));assert.equal((await db.profile.findUniqueOrThrow({where:{userId:cleanerMe.id}})).balance,0);
 const verification=await owner.request('/api/v1/admin/cleanups',{id:claim.data.id,approve:true,reason:'Test before and after evidence reviewed.'});assert.equal(verification.status,200,JSON.stringify(verification.data));const profile=await db.profile.findUniqueOrThrow({where:{userId:cleanerMe.id}});assert.equal(profile.balance,50);assert.equal(profile.currentStreak,1);assert.ok(await db.userAchievement.findUnique({where:{userId_achievementId:{userId:cleanerMe.id,achievementId:'cleanup-hero'}}}));
 const requestKey=crypto.randomUUID();const redeemed=await cleaner.request('/api/v1/rewards/demo-reward',{requestKey});assert.equal(redeemed.status,200,JSON.stringify(redeemed.data));const retry=await cleaner.request('/api/v1/rewards/demo-reward',{requestKey});assert.equal(retry.data.code,redeemed.data.code);assert.equal((await db.profile.findUniqueOrThrow({where:{userId:cleanerMe.id}})).balance,20);assert.equal((await cleaner.request('/api/v1/rewards/demo-reward',{requestKey:crypto.randomUUID()})).status,400);
 const child=new Client();await child.login('explorer@example.test');assert.equal((await child.request('/api/v1/reports')).status,403);assert.equal((await child.request('/api/v1/groups')).status,403);assert.equal((await child.request('/api/v1/admin')).status,403);assert.equal((await child.request('/api/v1/lessons')).status,200);
 const csrf=await fetch(`${base}/api/v1/reports`,{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://attacker.invalid'},body:'{}'});assert.equal(csrf.status,403);
 const harmful=new FormData();harmful.set('file',new File(['<script>alert(1)</script>'],'bad.png',{type:'image/png'}));assert.notEqual((await reporter.request('/api/v1/uploads',harmful)).status,200);
 await db.$disconnect();
});
