'use client';
import {useState,Suspense} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {signIn} from 'next-auth/react';
import {Sprout,Users,Building2} from 'lucide-react';
import {api,Brand,Button,Field,ErrorBox,Notice} from './ui';
import {EMIRATES} from '@/lib/domain';
export function AuthForm({mode}:{mode:'sign-in'|'sign-up'|'reset'}){const router=useRouter();const [kind,setKind]=useState('VOLUNTEER');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');return <main id="main-content" className="auth-page welcome-seed"><Brand/><p className="eyebrow">EVERY GREEN JOURNEY STARTS SOMEWHERE</p><h1>{mode==='sign-in'?'Welcome back.':mode==='sign-up'?'Let’s grow something good.':'A fresh start.'}</h1><p className="muted">{mode==='sign-up'?'Join a community that leaves places better than it finds them.':mode==='reset'?'We’ll send a secure link to your registered email.':'Your next small action can make a big difference.'}</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{if(mode==='sign-in'){const result=await signIn('credentials',{email:fields.email,password:fields.password,redirect:false});if(result?.error)throw new Error(result.error==='CredentialsSignin'?'Email or password is incorrect.':result.error);router.push('/home');}else if(mode==='reset'){const r=await api<{message:string}>('accounts/request-link',{email:fields.email,purpose:'RESET'});setMessage(r.message);}else{if(fields.password!==fields.confirmPassword)throw new Error('Passwords do not match.');const payload={...fields,kind,...(kind!=='CHILD'?{guardianEmail:undefined}:{}),...(kind!=='ORGANIZATION_ADMIN'?{organizationName:undefined}:{})};const r=await api<{message:string}>('accounts/register',payload);setMessage(r.message);}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {mode==='sign-up'&&<><div className="auth-kind">{[['VOLUNTEER','Volunteer · 12+',Users],['CHILD','Child · under 12',Sprout],['ORGANIZATION_ADMIN','Organization',Building2]].map(([value,title,Icon])=>{const I=Icon as typeof Users;return <button className={kind===value?'selected':''} type="button" key={String(value)} onClick={()=>setKind(String(value))}><I size={23}/>{String(title)}</button>;})}</div><div className="form-grid"><Field label={kind==='CHILD'?'Display name':'Your name'}><input name="name" minLength={2} maxLength={60} required autoComplete="name"/></Field><Field label="Username"><input name="username" pattern="[a-zA-Z0-9_]{3,24}" required autoComplete="username"/></Field><Field label="Date of birth" hint={kind==='CHILD'?'Only visible to your guardian and authorized staff.':'Used to check your account eligibility, then discarded.'}><input type="date" name="birthDate" required/></Field><Field label="Emirate"><select name="emirate">{EMIRATES.map(e=><option key={e}>{e}</option>)}</select></Field></div>{kind==='CHILD'&&<><Notice>Ask your parent or guardian to help you register. Your account stays private and locked until they approve.</Notice><Field label="Parent or guardian email"><input name="guardianEmail" type="email" required/></Field></>}{kind==='ORGANIZATION_ADMIN'&&<Field label="Organization name"><input name="organizationName" minLength={2} maxLength={100} required/></Field>}{kind==='VOLUNTEER'&&<Field label="What brings you here?"><select name="interest"><option value="BOTH">A little bit of both</option><option value="CLEAN">Clean reported trash</option><option value="REPORT">Report environmental problems</option><option value="EXPLORE">Just exploring</option></select></Field>}</>}
 <Field label={kind==='CHILD'?'Account email (guardian controlled)':'Email address'}><input name="email" type="email" required autoComplete="email"/></Field>{mode!=='reset'&&<Field label="Password" hint={mode==='sign-up'?'Use at least 12 characters. A memorable passphrase works well.':undefined}><input name="password" type="password" minLength={mode==='sign-up'?12:1} maxLength={128} required autoComplete={mode==='sign-up'?'new-password':'current-password'}/></Field>}{mode==='sign-up'&&<><Field label="Confirm password"><input name="confirmPassword" type="password" required minLength={12} autoComplete="new-password"/></Field><label className="check-label"><input type="checkbox" required/><span>I have read the <Link className="text-link" href="/policies/terms">terms</Link>, <Link className="text-link" href="/policies/privacy">privacy notice</Link>, and <Link className="text-link" href="/policies/safety">cleanup safety guidance</Link>.</span></label></>}<ErrorBox message={error}/>{message&&<Notice>{message}</Notice>}<Button busy={busy}>{mode==='sign-in'?'Sign in':mode==='reset'?'Send reset link':'Create my account'}</Button></form><div className="auth-footer">{mode==='sign-in'?<>New here? <Link href="/sign-up">Join GoGreen</Link><p><Link href="/reset">Forgot your password?</Link></p><p><Resend/></p></>:<Link href="/sign-in">Back to sign in</Link>}</div></main>;}
function Resend(){const [open,setOpen]=useState(false);const [message,setMessage]=useState('');return open?<form onSubmit={async e=>{e.preventDefault();try{setMessage((await api<{message:string}>('accounts/request-link',{email:new FormData(e.currentTarget).get('email'),purpose:'VERIFY'})).message);}catch(e){setMessage((e as Error).message);}}}><input type="email" name="email" placeholder="Your registered email" aria-label="Your registered email" required/><Button>Resend verification</Button>{message&&<span>{message}</span>}</form>:<button className="icon-button" style={{width:'auto',fontSize:12}} onClick={()=>setOpen(true)}>Resend verification email</button>;}
function VerifyInner(){const params=useSearchParams();const [error,setError]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const purpose=params.get('purpose');return <main className="auth-page" id="main-content"><Brand/><h1>{purpose==='GUARDIAN'?'A safer place to grow.':purpose==='RESET'?'Choose a new password.':'One last step.'}</h1><form onSubmit={async e=>{e.preventDefault();setBusy(true);try{const form=new FormData(e.currentTarget);const result=await api<{message:string}>('accounts/verify',{token:params.get('token'),password:form.get('password')||undefined,consent:form.get('consent')==='on'});setMessage(result.message);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{purpose==='GUARDIAN'&&<><p>Child accounts are private, cannot join public groups or claim cleanups, and have no private messaging. You control the account’s email and can close it in Settings.</p><Link className="text-link" href="/policies/child-safety">Read the child safety policy</Link><label className="check-label"><input type="checkbox" name="consent" required/><span>I am this child’s parent or legal guardian and approve this account.</span></label></>}{purpose==='RESET'&&<Field label="New password"><input name="password" type="password" minLength={12} maxLength={128} required/></Field>}<ErrorBox message={error}/>{message?<><Notice>{message}</Notice><Link href="/sign-in" className="button">Sign in</Link></>:<Button busy={busy}>{purpose==='GUARDIAN'?'Approve child account':purpose==='RESET'?'Save new password':'Verify my email'}</Button>}</form></main>;}
export function Verify(){return <Suspense><VerifyInner/></Suspense>;}
