'use client';
import {useState,Suspense} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {signIn} from 'next-auth/react';
import {api,Brand,Button,Field,ErrorBox,Notice} from './ui';
import {EMIRATES} from '@/lib/domain';
export function AuthForm({mode}:{mode:'sign-in'|'sign-up'|'reset'}){
 const router=useRouter();const [kind,setKind]=useState('VOLUNTEER');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');const [code,setCode]=useState('');
 return <main id="main-content" className="auth-page welcome-seed"><Brand/><p className="eyebrow">Every green journey starts somewhere</p><h1>{mode==='sign-in'?'Welcome back.':mode==='sign-up'?'Let’s grow something good.':'A fresh start.'}</h1><p className="muted">{mode==='sign-up'?'Create an account and sign in immediately. No email verification required.':mode==='reset'?'Use the private recovery code you saved at signup.':'Your next small action can make a big difference.'}</p>{code?<div className="stack"><Notice>{message}</Notice><Field label="Save your private recovery code" hint="Store this in your password manager. Anyone with this code can reset your password. It is shown only once."><textarea readOnly value={code}/></Field><Link href="/sign-in" className="button">I saved my code — sign in</Link></div>:<form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');setMessage('');const fields=Object.fromEntries(new FormData(e.currentTarget));try{
 if(mode==='sign-in'){const result=await signIn('credentials',{email:fields.email,password:fields.password,redirect:false});if(result?.error)throw new Error(result.error==='CredentialsSignin'?'Email or password is incorrect.':result.error);router.push('/home');}
 else if(mode==='reset'){if(fields.password!==fields.confirmPassword)throw new Error('Passwords do not match.');setMessage((await api<{message:string}>('accounts/recover',{email:fields.email,code:fields.code,password:fields.password})).message);}
 else{if(fields.password!==fields.confirmPassword)throw new Error('Passwords do not match.');const r=await api<{message:string;recoveryCode:string}>('accounts/register',{...fields,kind,...(kind!=='CHILD'?{guardianEmail:undefined}:{}),...(kind!=='ORGANIZATION_ADMIN'?{organizationName:undefined}:{})});setMessage(r.message);setCode(r.recoveryCode);}
 }catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>
 {mode==='sign-up'&&<><Field label="Account type"><select value={kind} onChange={e=>setKind(e.target.value)}><option value="VOLUNTEER">Volunteer · 12+</option><option value="CHILD">Child · under 12</option><option value="ORGANIZATION_ADMIN">Organization administrator · 18+</option></select></Field><div className="form-grid"><Field label="Display name"><input name="name" minLength={2} maxLength={60} required autoComplete="name"/></Field><Field label="Username"><input name="username" pattern="[a-zA-Z0-9_]{3,24}" required autoComplete="username"/></Field><Field label="Date of birth"><input type="date" name="birthDate" required/></Field><Field label="Emirate"><select name="emirate">{EMIRATES.map(e=><option key={e}>{e}</option>)}</select></Field></div>{kind==='CHILD'&&<><Notice>Your parent or guardian must have an account first. They approve your account from their own Settings page.</Notice><Field label="Guardian account email"><input name="guardianEmail" type="email" required/></Field></>}{kind==='ORGANIZATION_ADMIN'&&<Field label="Organization name"><input name="organizationName" minLength={2} maxLength={100} required/></Field>}</>}
 <Field label="Email address" hint={mode==='sign-up'?'Used as your sign-in identifier; no email is sent.':undefined}><input name="email" type="email" required autoComplete="email"/></Field>{mode==='reset'&&<Field label="Recovery code"><input name="code" pattern="[a-f0-9]{64}" required autoComplete="off"/></Field>}<Field label={mode==='reset'?'New password':'Password'} hint={mode!=='sign-in'?'Use at least 12 characters.':undefined}><input name="password" type="password" minLength={mode==='sign-in'?1:12} maxLength={128} required autoComplete={mode==='sign-in'?'current-password':'new-password'}/></Field>{mode!=='sign-in'&&<Field label="Confirm password"><input name="confirmPassword" type="password" minLength={12} maxLength={128} required autoComplete="new-password"/></Field>}{mode==='sign-up'&&<label className="check-label"><input type="checkbox" required/><span>I have read the <Link href="/policies/terms">terms</Link>, <Link href="/policies/privacy">privacy notice</Link>, and <Link href="/policies/safety">cleanup safety guidance</Link>.</span></label>}<ErrorBox message={error}/>{message&&<Notice>{message}</Notice>}<Button busy={busy}>{mode==='sign-in'?'Sign in':mode==='reset'?'Reset password':'Create my account'}</Button></form>}<div className="auth-footer">{mode==='sign-in'?<>New here? <Link href="/sign-up">Join GoGreen</Link><p><Link href="/reset">Forgot your password?</Link></p></>:<Link href="/sign-in">Back to sign in</Link>}</div></main>;
}
function VerifyInner(){const params=useSearchParams();const [message,setMessage]=useState('');return <main className="auth-page"><Brand/><h1>Existing account link</h1><form onSubmit={async e=>{e.preventDefault();try{const form=new FormData(e.currentTarget);setMessage((await api<{message:string}>('accounts/verify',{token:params.get('token'),password:form.get('password')||undefined})).message);}catch(e){setMessage((e as Error).message);}}}>{params.get('purpose')==='RESET'&&<Field label="New password"><input name="password" type="password" minLength={12} required/></Field>}<Button>Continue</Button>{message&&<Notice>{message}</Notice>}<Link href="/sign-in">Sign in</Link></form></main>;}
export function Verify(){return <Suspense><VerifyInner/></Suspense>;}
