'use client';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {createContext,useContext,useEffect,useState,type ReactNode} from 'react';
import {signOut} from 'next-auth/react';
import {Home,Map,Users,Trophy,Gift,User,Settings,Bell,BookOpen,Building2,CalendarDays,Search,LogOut,Shield,Menu,X,Leaf} from 'lucide-react';
import {Brand,Loading,ErrorBox,useApi,type Me} from './ui';
import {isAdmin} from '@/lib/domain';
const UserContext=createContext<Me|null>(null);
export function useMe(){return useContext(UserContext)!;}
const nav=[['/home','Overview',Home],['/map','Cleanup map',Map],['/groups','Community',Users],['/events','Events & missions',CalendarDays],['/achievements','Achievements',Trophy],['/rewards','Eco rewards',Gift],['/learn','Eco learning',BookOpen],['/organizations','Organizations',Building2]] as const;
export function Shell({children}:{children:ReactNode}){const {data:user,error}=useApi<Me>('me');const path=usePathname();const [open,setOpen]=useState(false);useEffect(()=>{if(user)document.documentElement.dataset.theme=user.profile.theme;},[user]);if(error)return <main className="auth-page"><Brand/><ErrorBox message={error}/><Link className="button" href="/sign-in">Sign in</Link></main>;if(!user)return <Loading/>;const links=user.role==='CHILD'?nav.filter(n=>['/home','/learn','/achievements','/rewards'].includes(n[0])):nav;return <UserContext value={user}><div className="app-shell"><aside className={`sidebar ${open?'sidebar-open':''}`}><div className="sidebar-top"><Brand/><button className="icon-button mobile-only" onClick={()=>setOpen(false)} aria-label="Close navigation"><X/></button></div><p className="nav-label">Your green journey</p><nav aria-label="Main navigation">{links.map(([href,title,Icon])=><Link onClick={()=>setOpen(false)} className={path.startsWith(href)?'active':''} key={href} href={href}><Icon size={19}/>{title}</Link>)}{isAdmin(user.role)&&<Link className={path.startsWith('/admin')?'active':''} href="/admin"><Shield size={19}/>Administration</Link>}</nav><div className="sidebar-bottom"><div className="sidebar-note"><Leaf size={24}/><strong>Small actions.<br/>Lasting change.</strong><p>Your next good deed is closer than you think.</p><Link href={user.role==='CHILD'?'/learn':'/map'}>Make a difference</Link></div><Link href="/settings" className="subnav"><Settings size={18}/>Settings</Link><button onClick={()=>signOut({callbackUrl:'/'})} className="subnav"><LogOut size={18}/>Sign out</button></div></aside><div className="app-main"><header className="topbar"><button className="icon-button mobile-only" aria-label="Open navigation" onClick={()=>setOpen(true)}><Menu/></button><span className="topbar-place">United Arab Emirates <span> / </span> {user.profile.emirate}</span><div className="topbar-actions">{user.role!=='CHILD'&&<Link className="icon-button" href="/search" aria-label="Search"><Search size={19}/></Link>}<Link className="icon-button" href="/notifications" aria-label="Notifications"><Bell size={19}/></Link><Link href="/profile" className="account"><span className="avatar">{user.name.slice(0,1)}</span><span>{user.name.split(' ')[0]}<small>{user.role==='CHILD'?'Young eco explorer':'Community member'}</small></span></Link></div></header><main id="main-content" className="workspace">{children}</main><footer className="app-footer">Growing a greener UAE, together.<Link href="/policies/community">Community guidelines</Link></footer></div><nav className="bottom-nav" aria-label="Mobile primary navigation">{(user.role==='CHILD'?[nav[0],nav[6],nav[4],nav[5]]:[nav[0],nav[1],nav[2],nav[5]]).map(([href,title,Icon])=><Link className={path===href?'active':''} href={href} key={href}><Icon size={20}/><span>{title}</span></Link>)}<Link href="/profile"><User size={20}/><span>Profile</span></Link></nav></div></UserContext>;}
