'use client';
import {useEffect,useState,useCallback,type ReactNode} from 'react';
import Link from 'next/link';
import {Leaf,LoaderCircle,Plus,X,MapPin,ShieldCheck} from 'lucide-react';
import {label,SEVERITIES} from '@/lib/domain';
export async function api<T>(path:string,data?:unknown):Promise<T>{const response=await fetch(`/api/v1/${path}`,data===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Please try again.');return result;}
export function useApi<T>(path:string){const [data,setData]=useState<T|null>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(true);const refresh=useCallback(()=>{setLoading(true);api<T>(path).then(d=>{setData(d);setError('');}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[path]);useEffect(()=>{let active=true;api<T>(path).then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[path]);return {data,error,loading,refresh};}
export function Brand(){return <Link href="/" className="brand"><span className="brand-mark"><Leaf size={23}/></span><span>GoGreen<span className="brand-country"> UAE</span></span></Link>;}
export function Button({children,busy=false,className='',...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{busy?:boolean}){return <button {...props} disabled={busy||props.disabled} className={`button ${className}`}>{busy&&<LoaderCircle size={17} className="spin"/>}{children}</button>;}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description?:string;action?:ReactNode}){return <header className="page-title"><div>{eyebrow&&<p className="eyebrow">{eyebrow}</p>}<h1>{title}</h1>{description&&<p className="muted">{description}</p>}</div>{action}</header>;}
export function Empty({title='A fresh start',children,href,cta}:{title?:string;children:ReactNode;href?:string;cta?:string}){return <div className="empty"><span className="icon-tile"><Leaf/></span><h3>{title}</h3><p>{children}</p>{href&&<Link className="button" href={href}>{cta}</Link>}</div>;}
export function Loading(){return <div className="skeleton-grid" aria-label="Loading" role="status">{[1,2,3].map(i=><div className="skeleton" key={i}/>)}</div>;}
export function ErrorBox({message}:{message:string}){return message?<p role="alert" className="error-box">{message}</p>:null;}
export function Notice({children}:{children:ReactNode}){return <p className="notice" role="status">{children}</p>;}
export function Badge({value}:{value:string}){return <span className={`badge badge-${value.toLowerCase()}`}>{label(value)}</span>;}
export function Field({label:caption,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{caption}</span>{children}{hint&&<small>{hint}</small>}</label>;}
export function Photo({id,alt,className=''}:{id?:string|null;alt:string;className?:string}){return id?<img className={`photo ${className}`} src={`/api/images/${id}`} alt={alt} loading="lazy"/>:<div className={`photo photo-empty ${className}`}><Leaf size={48}/></div>;}
export function UploadField({onUpload,label:caption='Photograph'}:{onUpload:(id:string)=>void;label?:string}){const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [id,setId]=useState('');return <div><Field label={caption} hint="JPG, PNG, or WebP · up to 8 MB · location metadata is removed"><input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setError('');try{const data=new FormData();data.append('file',file);const response=await fetch('/api/v1/uploads',{method:'POST',body:data});const result=await response.json();if(!response.ok)throw new Error(result.error);setId(result.id);onUpload(result.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}/></Field>{busy&&<Notice>Preparing and uploading your photo…</Notice>}{id&&<Photo id={id} alt="Your uploaded photo" className="upload-preview"/>}<ErrorBox message={error}/></div>;}
export function Modal({title,children,onClose}:{title:string;children:ReactNode;onClose:()=>void}){useEffect(()=>{const listener=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();};document.addEventListener('keydown',listener);return()=>document.removeEventListener('keydown',listener);},[onClose]);return <dialog open ref={el=>{if(el&&!el.matches(':modal')){el.close();el.showModal();}}} className="modal"><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header>{children}</dialog>;}
export type Report={id:string;title:string;description:string;category:string;severity:number;latitude:number;longitude:number;address:string;emirate:string;photoId:string;hazardous:boolean;status:string;createdAt:string;reporterId?:string;cleanups?:Cleanup[];riskSignals?:string[]};
export type Cleanup={id:string;reportId:string;cleanerId:string;status:string;afterPhotoId:string|null;notes:string;claimedAt:string;expiresAt:string;report:Report};
export type Me={id:string;name:string;email:string;username:string;role:string;profile:{bio:string;emirate:string;interest:string;theme:string;publicProfile:boolean;leaderboard:boolean;notifications:boolean;balance:number;lifetimePoints:number;currentStreak:number;longestStreak:number;lastActivityDay:string|null};levels:{id:number;name:string;minimumPoints:number}[];settings:{key:string;value:unknown}[];organizations:{organizationId:string;role:string;organization:{name:string}}[]};
export function ReportCard({report,onClick}:{report:Report;onClick?:()=>void}){const body=<><Photo id={report.photoId} alt={report.title}/><div className="report-card-body"><div className="row between"><Badge value={report.status}/><span className="muted small">{SEVERITIES[report.severity-1]}</span></div><h3>{report.title}</h3><p className="small muted"><MapPin size={14}/>{report.address}</p><div className="row between"><span className="tag">{report.category}</span>{report.hazardous?<span className="hazard"><ShieldCheck size={15}/> Authority review</span>:<span className="small green">{report.status==='CLEANED'?'Community impact':'Cleanup opportunity'}</span>}</div></div></>;return onClick?<button onClick={onClick} className="report-card">{body}</button>:<Link href={`/map?report=${report.id}`} className="report-card">{body}</Link>;}
export function AddLink({href,children}:{href:string;children:ReactNode}){return <Link href={href} className="button"><Plus size={17}/>{children}</Link>;}
